version: "3.9"

services:
     react-profile:
          container_name: profile-02
          build:
               context: .
               dockerfile: Dockerfile
          volumes:
               - ".:/app"
               - "/app/node_modules"
          ports:
               - "6020:80"
